### ISSUE TITLE
Cannot install TileServer with Node v.13.8.0

### ISSUE THREAD

**Issue by shihlinlu** [maptiler/tileserver-gl#449]
Has there been an update for TileServer to support Node v.11+? I could not install TileServer due to the node incompatibility issues. 
I am attempting to install TileServer v3.0.0 (latest version).

Environment details:
* Operating System: MacOS Catalina 10.15.4
* Installation source: npm via terminal

Please see the stack trace:

```my-computer % npm install -g tileserver-gl
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
/usr/local/bin/tileserver-gl -> /usr/local/lib/node_modules/tileserver-gl/src/main.js

> sqlite3@4.2.0 install /usr/local/lib/node_modules/tileserver-gl/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/usr/local/lib/node_modules/tileserver-gl/node_modules/sqlite3/lib/binding/node-v79-darwin-x64/node_sqlite3.node" is installed via remote

> @mapbox/mapbox-gl-native@5.0.2 install /usr/local/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native
> node-pre-gyp install --fallback-to-build=false

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v79-darwin-x64-Release.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/tileserver-gl/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:333:22)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/tileserver-gl/node_modules/request/request.js:1059:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:321:20)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:610:27)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:479:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:321:20)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:297:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:273:9)
node-pre-gyp ERR! System Darwin 19.4.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.8.0/bin/node" "/usr/local/lib/node_modules/tileserver-gl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native
node-pre-gyp ERR! node -v v13.8.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v79-darwin-x64-Release.tar.gz
npm WARN notsup Unsupported engine for tileserver-gl@3.0.0: wanted: {"node":">=10 <11"} (current: {"node":"13.8.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: tileserver-gl@3.0.0

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @mapbox/mapbox-gl-native@5.0.2 install: `node-pre-gyp install --fallback-to-build=false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @mapbox/mapbox-gl-native@5.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     *path not disclosed*
```

**Comment by chriswfoster** [comment]
I have this same issue. I'm running node v12.13.1.
Same error, almost exactly.

**Comment by petrsloup** [comment]
The installation log is quite clear about this:
```
npm WARN notsup Unsupported engine for tileserver-gl@3.0.0: wanted: {"node":">=10 <11"} (current: {"node":"13.8.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: tileserver-gl@3.0.0
```
(also see notes in the changelog: https://github.com/maptiler/tileserver-gl/releases/tag/v3.0.0)

`tileserver-gl` only supports **node v10** at the moment (due to mapbox-gl-native dependency). `tileserver-gl-light` package (without rasterization) supports **node v10+**
