### ISSUE TITLE
Custom styles gives ReferenceError: file is not defined

### ISSUE THREAD

**Issue by HeyHugo** [maptiler/tileserver-gl#466]
When trying to use custom styles the server can't start and logs show:
```
Starting tileserver-gl v3.0.0
Using specified config file from config.json
Starting server
ReferenceError: file is not defined
    at serve_style.add (/usr/src/app/src/server.js:139:44)
    at Proxy.add (/usr/src/app/src/serve_style.js:115:28)
    at addStyle (/usr/src/app/src/server.js:121:31)
    at start (/usr/src/app/src/server.js:182:5)
    at module.exports.opts (/usr/src/app/src/server.js:469:19)
    at startServer (/usr/src/app/src/main.js:80:29)
    at fs.stat (/usr/src/app/src/main.js:211:12)
    at FSReqWrap.oncomplete (fs.js:154:5)
```

>- Version of the TileServer GL software you have used

The one is latest docker image (`maptiler/tileserver-gl`)

>- Version and name of the operating system you use or other details of your setup

I'm using the docker image, so should be debian stretch or debian buster as base I guess.

>- Information about your used config / styles / vector tiles
 
config.json:
```json
{
  "options": {
    "paths": {
      "root": "",
      "fonts": "",
      "sprites": "",
      "styles": "styles",
      "mbtiles": "data"
    },
    "domains": [
      "localhost:8080",
    ],
    "formatQuality": {
      "jpeg": 80,
      "webp": 90
    },
    "maxScaleFactor": 3,
    "maxSize": 2048,
    "pbfAlias": "pbf",
    "serveAllFonts": true,
    "serveAllStyles": true,
    "serveStaticMaps": true,
    "tileMargin": 0
  },
  "styles": {
    "osmbright": {
      "style": "osmbright/style-local.json",
      "serve_rendered": true,
      "serve_data": true,
      "tilejson": {
        "bounds": [
          11.0273686052, 55.3617373725, 23.9033785336, 69.1062472602
        ]
      }
    }
  },
  "data": {
    "sweden": {
      "mbtiles": "tiles.mbtiles"
    }
  }
}
```
When removing the styles section of the config the server runs and I can just see a basic map:
<img width="1004" alt="Screenshot 2020-07-14 at 16 06 33" src="https://user-images.githubusercontent.com/1010517/87435523-2449ee00-c5ec-11ea-84ab-725d83fc2ecb.png">

The style I'm trying to use is downloaded from here: https://github.com/openmaptiles/osm-bright-gl-style/releases
I get the same error when trying other styles from openmaptiles repos. I've checked that the volume with styles are mounted in the correct place in the container.

Thankful for any help :)

**Comment by HeyHugo** [comment]
I've solved this.

I found that the styles-local.json file referenced the data source like this:
```json
  "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "mbtiles://{v3}"
    }
  }
```

Changing the `data` object in my config.json like this fixed it:
```json
  "data": {
    "v3": {
      "mbtiles": "tiles.mbtiles"
    }
  }
```
(note I'm referencing "v3" here now instead of "sweden")
