### ISSUE TITLE
Complaining about missing sqlite3 module when installed with npm

### ISSUE THREAD

**Issue by tmlmt** [maptiler/tileserver-gl#522]
Versions:
- Ubuntu 20.04.2
- Node 10.19.0
- npm 6.14.4

I've installed tileserver-gl-light using: `npm install -g tileserver-gl-light`

But when trying to run it: `tileserver-gl-light myfile.mbtiles`, I get the following error:

```
usr/local/lib/node_modules/tileserver-gl-light/node_modules/sqlite3/lib/sqlite3-binding.js:1
Error: Cannot find module '/usr/local/lib/node_modules/tileserver-gl-light/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node'
Require stack:
- /usr/local/lib/node_modules/tileserver-gl-light/node_modules/sqlite3/lib/sqlite3-binding.js
- /usr/local/lib/node_modules/tileserver-gl-light/node_modules/sqlite3/lib/sqlite3.js
- /usr/local/lib/node_modules/tileserver-gl-light/node_modules/@mapbox/mbtiles/lib/mbtiles.js
- /usr/local/lib/node_modules/tileserver-gl-light/src/main.js
    at Object.<anonymous> (/usr/local/lib/node_modules/tileserver-gl-light/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

Can anyone help?

**Comment by hellorayza** [comment]
Why hasn't anyone maintained it for a long time....
