### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by wuqihui** [maptiler/tileserver-gl#586]
I have used  ‘’npm install ' command to install dependencies. bug When I run the project ,it info Failed.
how i could solve this problem

Uncaught Error d:\Source\TileServerSource\tileserver-gl\node_modules\@mapbox\mapbox-gl-native\platform\node\index.js:1
Error: Cannot find module '../../lib/node-v83/mbgl'
Require stack:
- d:\Source\TileServerSource\tileserver-gl\node_modules\@mapbox\mapbox-gl-native\platform\node\index.js
- d:\Source\TileServerSource\tileserver-gl\src\serve_rendered.js
- d:\Source\TileServerSource\tileserver-gl\src\server.js
- d:\Source\TileServerSource\tileserver-gl\src\main.js
    at MODULE_NOT_FOUND (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:218084)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:255867)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:253960)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:252173)
    at t (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:279775)
    at n (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:279589)
    at <anonymous> (d:\Source\TileServerSource\tileserver-gl\node_modules\@mapbox\mapbox-gl-native\platform\node\index.js:5:12)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:251206)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:245054)
    at bl (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:245412)
    at kl (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:247659)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:288137)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:228903)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Ph (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:286187)
    at u (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:288319)
    at o (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:287137)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:284879)
    at apply (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:199341)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:251778)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:251820)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:254242)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:254318)
    at Su (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:228927)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:254092)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:252173)
    at t (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:279775)
    at require (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:279589)
    at <anonymous> (d:\Source\TileServerSource\tileserver-gl\src\serve_rendered.js:20:14)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:251206)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:245054)
    at bl (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:245412)
    at kl (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:247659)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:288137)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:228903)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Ph (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:286187)
    at u (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:288319)
    at o (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:287137)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:284879)
    at apply (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:199341)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:251778)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:251820)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:254242)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:254318)
    at Su (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:228927)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:254092)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:252173)
    at t (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:279775)
    at require (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:279589)
    at <anonymous> (d:\Source\TileServerSource\tileserver-gl\src\server.js:29:20)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:251206)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:245054)
    at bl (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:245412)
    at kl (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:247659)
    at u (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:287740)
    at o (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:287137)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:284879)
    at apply (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:199341)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:231006)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:231041)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:231254)
    at Su (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:228587)
    at ku (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:230341)
    at _c (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:258239)
    at <anonymous> (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:296060)
    at require (file:///D:/node_data/node_global/node_modules/tileserver-gl-light/node_modules/esm/esm.js:1:279589)
    at startServer (d:\Source\TileServerSource\tileserver-gl\src\main.js:80:10)
    at <anonymous> (d:\Source\TileServerSource\tileserver-gl\src\main.js:211:12)
    at <anonymous> (fs.js:177:5)
    at topLevelDomainCallback (domain.js:138:15)
    at callbackTrampoline (internal/async_hooks.js:121:14)
    --- FSREQCALLBACK ---
    at init (internal/inspector_async_hook.js:25:19)
    at emitInitNative (internal/async_hooks.js:185:43)
    at stat (fs.js:1015:15)
    at <anonymous> (d:\Source\TileServerSource\tileserver-gl\src\main.js:178:4)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Module._load (internal/modules/cjs/loader.js:938:14)
    at executeUserEntryPoint (internal/modules/run_main.js:71:12)
    at <anonymous> (internal/main/run_main_module.js:17:47)

I use

**Comment by acalcutt** [comment]
The old version which used mapbox-native only supported up to node 10, which is the cause of that error. There were no mapbox binaries past node 10.

The version released today recommends a minimum of node 14.20 and recommends node 16. The maplibre-native release is build for Ubuntu 20.04 X64 and MacOS 12 X64, so it is recommended to be on one of those OS versions if you are running without docker.
