### ISSUE TITLE
tileserver-gl: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v93-linux-x64-Release.tar.gz

### ISSUE THREAD

**Issue by T0mThomson** [maptiler/tileserver-gl#590]
## Problem

When installing the package `tileserver-gl` via npm I get the followning error:

## Error Message

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'tileserver-gl@3.1.1',
npm WARN EBADENGINE   required: { node: '>=10 <11' },
npm WARN EBADENGINE   current: { node: 'v16.15.1', npm: '8.12.1' }
npm WARN EBADENGINE }
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.10.3: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build=false
npm ERR! 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v93-linux-x64-Release.tar.gz
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.10.3
npm ERR! node-pre-gyp info using node@16.15.1 | linux | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download
npm ERR! node-pre-gyp info check checked for "/usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native/lib/node-v93/mbgl.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v93-linux-x64-Release.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v93-linux-x64-Release.tar.gz
npm ERR! node-pre-gyp ERR! install error
npm ERR! node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/@mapbox/mapbox-gl-native/v5.0.2/node-v93-linux-x64-Release.tar.gz
npm ERR! node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/tileserver-gl/node_modules/node-pre-gyp/lib/install.js:137:27)
npm ERR! node-pre-gyp ERR! stack     at Request.emit (node:events:539:35)
npm ERR! node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/tileserver-gl/node_modules/request/request.js:1059:10)
npm ERR! node-pre-gyp ERR! stack     at ClientRequest.emit (node:events:527:28)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
npm ERR! node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:494:22)
npm ERR! node-pre-gyp ERR! stack     at TLSSocket.emit (node:events:527:28)
npm ERR! node-pre-gyp ERR! stack     at addChunk (node:internal/streams/readable:315:12)
npm ERR! node-pre-gyp ERR! stack     at readableAddChunk (node:internal/streams/readable:289:9)
npm ERR! node-pre-gyp ERR! System Linux 5.15.0-33-generic
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/tileserver-gl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
npm ERR! node-pre-gyp ERR! cwd /usr/lib/node_modules/tileserver-gl/node_modules/@mapbox/mapbox-gl-native
npm ERR! node-pre-gyp ERR! node -v v16.15.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.10.3
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-08T11_20_04_663Z-debug-0.log
```

## System specifications

- Node version: `v16.15.1`
- NPM version: `8.12.1`
- Operating System: `Ubuntu 22.04 LTS`

**Comment by T0mThomson** [comment]
It works using node `v10.24.1`
