### ISSUE TITLE
Error: "libicui18n.so.66: cannot open shared object file" when try to run tileserver-gl on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by Korolev-Oleg** [maptiler/tileserver-gl#973]
```shell
> tileserver-gl 
node:internal/modules/cjs/loader:1340
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libicui18n.so.66: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/home/map/.nvm/versions/node/v18.17.1/lib/node_modules/tileserver-gl/node_modules/@maplibre/maplibre-gl-native/platform/node/index.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

I tried fixing this error by installing libicu-dev and the [requirements](https://tileserver.readthedocs.io/en/latest/installation.html#native-dependencies) from the documentation, but it didn't work.

`node -v v18.17.1`
`Ubuntu 22.04.3 LTS`

**Comment by Korolev-Oleg** [comment]
It should be noted that `teleserver-gl-light` operates without errors.

**Comment by scara** [comment]
Hi @Korolev-Oleg,
> It should be noted that `tileserver-gl-light` operates without errors.

you should IMHO go with the `docker` option for `tileserver-gl` since `maplibre-gl-native` requires some specific libs with specific versions - you could create a symlink against newer versions.
BTW you can try with `sudo apt-get update && sudo apt-get install libicu66`.

HTH,
Matteo

**Comment by acalcutt** [comment]
It is not possible right now to run on 22.04 without providing your own maplibre-native binary files. The maplibre-native binaries are built on Ubuntu 20.04, so they have hard dependencies on the versions it was built with.

We found in https://github.com/maptiler/tileserver-gl/issues/643 that Ubuntu 22.04 uses libicu70 and has no libicu66, so maplibre-native fails. You can see this in the ct test with this error it is getting

Error: libicui18n.so.66: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1249:18)
    at Module.load (node:internal/modules/cjs/loader:[10](https://github.com/maptiler/tileserver-gl/actions/runs/3804864684/jobs/6472538658#step:10:11)43:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/runner/work/tileserver-gl/tileserver-gl/node_modules/@maplibre/maplibre-gl-native/platform/node/index.js:5:12)
    at Module._compile (node:internal/modules/cjs/loader:[11](https://github.com/maptiler/tileserver-gl/actions/runs/3804864684/jobs/6472538658#step:10:12)65:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:[12](https://github.com/maptiler/tileserver-gl/actions/runs/3804864684/jobs/6472538658#step:10:13)19:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:[16](https://github.com/maptiler/tileserver-gl/actions/runs/3804864684/jobs/6472538658#step:10:17)9:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:[19](https://github.com/maptiler/tileserver-gl/actions/runs/3804864684/jobs/6472538658#step:10:20)3:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:[24](https://github.com/maptiler/tileserver-gl/actions/runs/3804864684/jobs/6472538658#step:10:25))
    at async file:///home/runner/work/tileserver-gl/tileserver-gl/src/server.js:33:3
Error: Process completed with exit code 1.
We've had some discussion on the maplibre-native slack about how to get the binary to be more portable, but right now it has dependecies
https://osmus.slack.com/archives/C02B2CBSNBU/p1670899965718649


Right now as @scara said. If you want to keep the OS you are on, docker is the best option. You could also switch to 20.04 and it should work without docker.

**Comment by acalcutt** [comment]
See this for how I got 22.04 to work in testing
https://github.com/maptiler/tileserver-gl/issues/643#issuecomment-1323169811

If you did try that you might want to checkout maplibre-native at the last node release version
https://github.com/maplibre/maplibre-native/releases/tag/node-v5.2.0
since there has been lots of changes for metal support that i'm not sure are ready for the node binary build
